# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchworks-installer" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "37df4bed1cb476b600bad8b7e3e92bc07269c7a06cbf081fab102a3b54150ca8"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "96a650a9cfac72c39b174b611345944eae67f567856f5c7f8e058f0404b82b26"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc7ef5e7876c4c1f05ca582086e750aa3f1e2ebe679ba0205ed8eba5916e3b29"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b95ba1037b3249bcbf1fc3af7ef3cec87c68ec39303a7ebfd555d02f660cea15"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "patchworks-installer"
  desc "Patchworks self-hosted installer"
  homepage "https://github.com/gopatchworks/selfhosted"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchworks-installer"

  # No zap stanza required
end
