# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchworks-installer" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "9099bf6e535c6bd3fee9243951b5ed646c966bb01096d1d8cdf8e791e2595c28"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4c18bd878cb9894d511940fed5d4ede93824f3bd7f96d145b912113b28ce9d2"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "329591ed002771581ea2760bddc077ef176c9e216defb985b3040a657464e1a6"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c10a327c09823d21ba012c3d0939442066ee2c1ab83dad916055f30b172d46d"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "patchworks-installer"
  desc "Patchworks self-hosted installer"
  homepage "https://github.com/gopatchworks/selfhosted"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchworks-installer"

  # No zap stanza required
end
