# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchworks-installer" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "15a72982d14cc43c0e6a119bab85508d76ebfe109034de21c1523b8ab9057164"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "00580255b74d2f6c5fda4bc9592fdf78dd118a886b0cc6cd2f56e53706612933"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ec60a87fd7e2f6f40b8b66a3b24594b7b266d324df13cb507775e0b5d8354b6"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c36388ae2edf61001fa84bd592294bbb7b5bd7a848084fcc3ef36054d38c381"
      url "https://github.com/gopatchworks/selfhosted/releases/download/v#{version}/patchworks-installer_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "patchworks-installer"
  desc "Patchworks self-hosted installer"
  homepage "https://github.com/gopatchworks/selfhosted"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchworks-installer"

  # No zap stanza required
end
